"""
Render every vocabulary word to audio using macOS's Mexican Spanish voice.

Device text-to-speech is a lottery: a browser with no Spanish voice reads
Spanish with an English mouth, which teaches the wrong pronunciation. Shipping
recordings makes every device sound the same, and `expo-speech` stays as the
fallback for words added since the last render.

Paulina is a macOS system voice. Redistributing her output is fine for a
personal build and would need re-rendering with a commercially licensed voice
before any app-store release.

Usage:  python tools/make_speech.py
"""
import json
import subprocess
import sys
from pathlib import Path

VOICE = 'Paulina'          # es_MX
BITRATE = '32000'          # ~8KB per word; speech needs no more
SEED = Path('data/seed')
OUT = Path('apps/app/assets/speech')
INDEX = Path('apps/app/storage/speech.ts')


def words() -> list[dict]:
    out = []
    for f in sorted(SEED.glob('*.json')):
        out.extend(json.loads(f.read_text()))
    return out


def render(text: str, dest: Path) -> None:
    wav = dest.with_suffix('.wav')
    subprocess.run(
        ['say', '-v', VOICE, '--data-format=LEI16@22050',
         '--file-format=WAVE', '-o', str(wav), text],
        check=True)
    subprocess.run(
        ['afconvert', '-f', 'm4af', '-d', 'aac', '-b', BITRATE,
         str(wav), str(dest)],
        check=True, capture_output=True)
    wav.unlink()


def main() -> None:
    if subprocess.run(['say', '-v', VOICE, ''], capture_output=True).returncode:
        sys.exit(f'Voice "{VOICE}" is not installed. '
                 'System Settings > Accessibility > Spoken Content > System Voice.')

    OUT.mkdir(parents=True, exist_ok=True)
    entries = []
    for w in words():
        dest = OUT / f'{w["id"]}.m4a'
        if not dest.exists():                 # re-running is cheap
            render(w['es'], dest)
        entries.append(w['id'])

    # Metro cannot resolve a computed require path, so the index is generated
    # with one literal require per word.
    lines = [
        '// Generated by tools/make_speech.py — do not edit by hand.',
        '',
        '/** Word id to its bundled pronunciation. */',
        'export const RECORDINGS: Record<string, number> = {',
    ]
    lines += [f"  {json.dumps(i)}: require('../assets/speech/{i}.m4a')," for i in sorted(entries)]
    lines += ['};', '']
    INDEX.write_text('\n'.join(lines))

    total = sum(f.stat().st_size for f in OUT.glob('*.m4a'))
    print(f'{len(entries)} recordings, {total / 1024 / 1024:.1f} MB total')


if __name__ == '__main__':
    main()
